"""
Auto Cookie Export - Uses Playwright to launch a Chromium browser,
lets you log in to target sites, then exports cookies on browser close.

No interaction required - just run it and the browser will open.
Close the browser window when done.
"""
import os
import sys
import json
import shutil
import time
from datetime import datetime

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    print("Installing Playwright...")
    os.system("pip install playwright")
    os.system("playwright install chromium")
    from playwright.sync_api import sync_playwright


def export_cookies(cookies, output_path):
    """Export cookies to Netscape cookies.txt format."""
    count = 0
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write(f"# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
        f.write("# Generated by auto_cookies.py\n\n")

        for cookie in cookies:
            domain = cookie.get("domain", "")
            if not domain:
                continue

            # Domain format
            if not domain.startswith("."):
                domain = "." + domain

            # Normalize domain: .www.X.com -> .X.com for yt-dlp compatibility
            # yt-dlp expects cookies on the main domain, not www subdomain
            if domain.startswith(".www."):
                domain = domain[4:]  # Remove ".www" prefix

            path = cookie.get("path", "/") or "/"
            is_secure = "TRUE" if cookie.get("secure", False) else "FALSE"
            name = cookie.get("name", "")
            value = cookie.get("value", "")

            if not name or not value:
                continue

            # Format expiry
            expires = cookie.get("expires", 0)
            if expires and expires > 0:
                expires = int(expires)
            else:
                expires = 0

            # Escape value
            value = value.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")

            f.write(f"{domain}\tTRUE\t{path}\t{is_secure}\t{expires}\t{name}\t{value}\n")
            count += 1

    return count


def main():
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cookies.txt")

    print("=" * 60)
    print("  Auto Cookie Export Tool")
    print("=" * 60)
    print()
    print("A Chromium browser will open shortly.")
    print("Navigate to your target sites and log in.")
    print("When finished, close the browser window to export cookies.")
    print()
    print("Supported sites: Bilibili, TikTok, YouTube, Douyin, etc.")
    print()
    print("Starting browser...")
    print()

    # Clean up temp directory if it exists
    temp_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "playwright_temp")
    if os.path.exists(temp_dir):
        try:
            shutil.rmtree(temp_dir, ignore_errors=True)
        except:
            pass

    with sync_playwright() as p:
        # Launch browser with user data directory for persistence
        browser = p.chromium.launch(
            headless=False,
            args=[
                "--no-sandbox",
                "--disable-blink-features=AutomationControlled",
            ],
        )

        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
            viewport={"width": 1280, "height": 800},
        )

        page = context.new_page()

        # Show welcome page with links
        page.set_content(f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                    max-width: 700px;
                    margin: 50px auto;
                    padding: 20px;
                    background: #f8fafc;
                    color: #334155;
                }}
                h1 {{ color: #1e293b; text-align: center; margin-bottom: 10px; }}
                .subtitle {{ text-align: center; color: #64748b; margin-bottom: 30px; }}
                .card {{
                    background: white;
                    border-radius: 12px;
                    padding: 20px;
                    margin: 15px 0;
                    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                }}
                .card h3 {{ margin: 0 0 15px 0; color: #1e293b; }}
                .link-grid {{
                    display: grid;
                    grid-template-columns: 1fr 1fr;
                    gap: 10px;
                }}
                .link-btn {{
                    display: block;
                    padding: 12px 16px;
                    background: #6366f1;
                    color: white;
                    text-decoration: none;
                    border-radius: 8px;
                    text-align: center;
                    font-weight: 500;
                    transition: background 0.2s;
                }}
                .link-btn:hover {{ background: #4f46e5; }}
                .link-btn.tiktok {{ background: #000000; }}
                .link-btn.youtube {{ background: #ff0000; }}
                .link-btn.douyin {{ background: #000000; }}
                .link-btn.kuaishou {{ background: #ff6600; }}
                .link-btn.xiaohongshu {{ background: #ff2442; }}
                .link-btn.instagram {{ background: linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888); }}
                .link-btn.twitter {{ background: #1da1f2; }}
                .link-btn.bilibili {{ background: #fb7299; }}
                .status {{
                    text-align: center;
                    padding: 15px;
                    background: #f0fdf4;
                    border-radius: 8px;
                    margin-top: 20px;
                    border: 1px solid #bbf7d0;
                }}
                .status .count {{ font-size: 24px; font-weight: bold; color: #16a34a; }}
                .hint {{ color: #94a3b8; font-size: 14px; margin-top: 10px; text-align: center; }}
            </style>
        </head>
        <body>
            <h1>🍪 Cookie Export Tool</h1>
            <p class="subtitle">Navigate to your target sites below and log in</p>

            <div class="card">
                <h3>📺 Video Platforms</h3>
                <div class="link-grid">
                    <a href="https://www.bilibili.com" target="_blank" class="link-btn bilibili">Bilibili</a>
                    <a href="https://www.douyin.com" target="_blank" class="link-btn douyin">抖音</a>
                    <a href="https://www.kuaishou.com" target="_blank" class="link-btn kuaishou">快手</a>
                    <a href="https://www.xiaohongshu.com" target="_blank" class="link-btn xiaohongshu">小红书</a>
                    <a href="https://www.tiktok.com" target="_blank" class="link-btn tiktok">TikTok</a>
                    <a href="https://www.youtube.com" target="_blank" class="link-btn youtube">YouTube</a>
                </div>
            </div>

            <div class="card">
                <h3>📱 Social Media</h3>
                <div class="link-grid">
                    <a href="https://www.instagram.com" target="_blank" class="link-btn instagram">Instagram</a>
                    <a href="https://twitter.com" target="_blank" class="link-btn twitter">Twitter/X</a>
                </div>
            </div>

            <div class="status">
                <div>Cookies in this session</div>
                <div class="count" id="cookie-count">0</div>
            </div>

            <p class="hint">When finished, close this browser window to export cookies</p>

            <script>
                function updateCount() {{
                    try {{
                        var count = document.cookie.split(';').filter(c => c.trim()).length;
                        document.getElementById('cookie-count').textContent = count;
                    }} catch(e) {{}}
                }}
                setInterval(updateCount, 2000);
                updateCount();
            </script>
        </body>
        </html>
        """)

        print("Browser opened! Log in to your target sites.")
        print("Close the browser window when done.")
        print()

        # Wait for browser close
        # We detect close by trying to interact with the page
        try:
            while True:
                try:
                    page.evaluate("1+1")
                    time.sleep(1)
                except:
                    break
        except:
            pass

        # Get all cookies before closing
        try:
            cookies = context.cookies()
            print(f"Found {len(cookies)} cookies")

            if cookies:
                count = export_cookies(cookies, output_path)
                print(f"Exported {count} cookies to {output_path}")
            else:
                print("No cookies found. Make sure you logged in to some sites.")
        except Exception as e:
            print(f"Error getting cookies: {e}")

        browser.close()

    # Cleanup temp directory
    if os.path.exists(temp_dir):
        try:
            shutil.rmtree(temp_dir, ignore_errors=True)
        except:
            pass

    print()
    print("=" * 60)
    if os.path.exists(output_path):
        file_size = os.path.getsize(output_path)
        print(f"Done! cookies.txt created ({file_size} bytes)")
        print(f"Location: {output_path}")
        print()
        print("Copy this file to: F:\\去水印视频工具\\cookies.txt")
    else:
        print("No cookies.txt created. Please try again.")
    print("=" * 60)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted")
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
