"""
Export browser cookies using Playwright.
1. Launches a headed Chromium browser
2. You navigate to target sites and log in
3. Close the browser when done
4. Cookies are automatically exported to cookies.txt

Usage:
    pip install playwright
    playwright install chromium
    python export_cookies_playwright.py
"""
import os
import json
from datetime import datetime, timezone

from playwright.sync_api import sync_playwright


def convert_expiry(expiry_value):
    """Convert Playwright expiry to Unix timestamp."""
    if not expiry_value:
        return 0
    if expiry_value > 10**12:
        # Windows FILETIME to Unix
        return int((expiry_value - 116444736000000000) / 1000000)
    return int(expiry_value)


def main():
    print("=" * 60)
    print("Playwright Cookie Export Tool")
    print("=" * 60)
    print()
    print("This tool will launch a browser window for you to use.")
    print("Navigate to your target sites and log in as needed.")
    print("When finished, close the browser window to export cookies.")
    print()
    print("Supported sites: Bilibili, TikTok, YouTube, Instagram, etc.")
    print()
    input("Press Enter to launch browser...")
    print()

    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cookies.txt")

    with sync_playwright() as p:
        # Launch Chromium with user data directory to get existing cookies
        # Use a temporary user data directory for this session
        temp_user_data = os.path.join(os.path.dirname(os.path.abspath(__file__)), "playwright_temp")
        os.makedirs(temp_user_data, exist_ok=True)

        print("Launching Chromium browser...")
        browser = p.chromium.launch(
            headless=False,
            args=["--no-sandbox"],
            user_data_dir=temp_user_data,
        )

        context = browser.new_context()
        page = context.new_page()

        # Navigate to a welcome page
        page.goto("about:blank")
        page.set_content("""
            <html>
            <body style="font-family: sans-serif; padding: 40px; text-align: center;">
                <h1>🍪 Cookie Export Tool</h1>
                <p>Use this browser to navigate to your target sites and log in.</p>
                <p>When finished, <strong>close this browser window</strong> to export cookies.</p>
                <hr>
                <p>Common sites:</p>
                <ul style="text-align: left; display: inline-block;">
                    <li><a href="https://www.bilibili.com" target="_blank">Bilibili (B站)</a></li>
                    <li><a href="https://www.youtube.com" target="_blank">YouTube</a></li>
                    <li><a href="https://www.instagram.com" target="_blank">Instagram</a></li>
                    <li><a href="https://www.tiktok.com" target="_blank">TikTok</a></li>
                    <li><a href="https://www.xiaohongshu.com" target="_blank">小红书</a></li>
                </ul>
                <hr>
                <p style="color: #666;">Current cookies in this session: <span id="cookie-count">0</span></p>
                <script>
                    function updateCount() {
                        document.getElementById('cookie-count').textContent = document.cookie.split(';').length;
                    }
                    setInterval(updateCount, 1000);
                    updateCount();
                </script>
            </body>
            </html>
        """)

        print("Browser launched. Navigate to your target sites.")
        print("Close the browser window when done.")

        # Wait for browser to be closed
        try:
            page.wait_for_event("close", timeout=86400000)  # Wait up to 24 hours
        except:
            pass  # Timeout is fine

        # Get all cookies
        cookies = context.cookies()
        print(f"\nFound {len(cookies)} cookies")

        if cookies:
            # Write to cookies.txt
            with open(output_path, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write(f"# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
                f.write("# Generated by export_cookies_playwright.py\n\n")

                count = 0
                for cookie in cookies:
                    # Domain format: Netscape needs dot prefix
                    domain = cookie.get("domain", "")
                    if domain and not domain.startswith("."):
                        domain = "." + domain

                    path = cookie.get("path", "/") or "/"
                    is_secure = "TRUE" if cookie.get("secure", False) else "FALSE"

                    # Format expiry
                    expires = cookie.get("expires", 0)
                    if expires and expires > 0:
                        if expires > 10**12:
                            expires = int((expires - 116444736000000000) / 1000000)
                        else:
                            expires = int(expires)
                    else:
                        expires = 0

                    name = cookie.get("name", "")
                    value = cookie.get("value", "")

                    # Escape value
                    value = value.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")

                    f.write(f"{domain}\tTRUE\t{path}\t{is_secure}\t{expires}\t{name}\t{value}\n")
                    count += 1

            print(f"Exported {count} cookies to {output_path}")
        else:
            print("No cookies found. You may need to log in to some sites first.")

        browser.close()

        # Cleanup temp directory
        try:
            import shutil
            shutil.rmtree(temp_user_data, ignore_errors=True)
        except:
            pass

    print("\nDone! Place cookies.txt in the project root directory.")


if __name__ == "__main__":
    main()
